apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: gcr.io/master-streamer-425115-n0/node-api:v1
        ports:
        - containerPort: 3000
      env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: password
      - name: POSTGRES_HOST
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: host
      - name: POSTGRES_PORT
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: port
      - name: POSTGRES_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: database
