apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret
spec:
  template: 
    spec:
      containers:
      - name: gcp-sm-to-k8s
        image: google/cloud-sdk:latest
        command: ["sh", "-c", "echo $(gcloud secrets versions access latest --secret=db-credentials) | kubectl create secret generic db-credentials --from-literal=database-url=/dev/stdin"]
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - name: gcp-service-account
          mountPath: /var/secrets/google
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: gcp-service-account
        secret:
          secretName: gcp-service-account
